### ISSUE TITLE
getInjectionToken中的service是怎么使用的？

### ISSUE THREAD

**Issue by wangguo1230** [DayZFE/vue-injection-helper#2]
不是很懂这个service是怎么使用的，求大佬解惑，另外大佬的文章能不能发我一下，看见的时候已经没了 🤦‍♀️

**Comment by plightfield** [comment]
还在完善中，完成了会有新文章发出来，不过不会提到ddd
这个api工具中，getMockInstance 和 getInjectionToken 都是帮助你有更好 ts 体验的
const mockService = getMockInstance(SomeService)
之后可以通过 typeof mockService 自动拿到类型
const token = getInjectionToken(SomeService)
之后 inject 的时候，也可以自动拿到类型
hidePrivider 是对相同 token provide 一个 undefined，防止子孙组件拿到值
OptionalInjectionModule 是声明一个核心领域，这部分还需要大改，大概意思你可以认为是将一个领域模块的逻辑全权交由领域外来控制，类似 form 的所有逻辑，都在form之外声明和控制，这部分处理模块间通讯，这部分大改完我会发文章
Aggregation 是聚合操作，你可以用 Vuex 的 getters 聚合 state 来对比，区别是 Vuex getters 拿的只是响应式的状态，而 Aggregation 拿的是聚合根（也就是 OptionalInjectionModule 的响应式对象实例）的一部分，它自带响应式和响应式控制（类比 action），其后果就是，你在开发时不用考虑视图，视图会在服务注入后主动来响应你

**Comment by wu-yan-Wang** [comment]
大佬，我对ts不是很熟悉,我看您的`getMockInstance`代码中只是返回了一个undefined,不是很懂这个是什么意思,还有`getInjectionToken `方法中没有用到service,也不是很懂,

**Comment by wu-yan-Wang** [comment]
大佬,我对ts不是很懂,我列出我的几条疑问:
1. `getMockInstance`中我看return了一个undefined指向了结果,是不是可以理解为创建`SomeService `的时候声明了返回值,通过`getMockInstance`包装一下可以智能提示返回值的结构,但这是不是需要把`SomeService `返回过来才能起作用啊?
2. `getInjectionToken`注入`SomeService`后,会返回一个`Symbol`的token,子组件或其他的地方去使用,那是不是需要把这个token去全局维护?
3. 这个方式是不是只适用于子父组件,如果使用vue router的话,这个服务是不是就需要顶层注入,然后子组件再去inject，那这样和vuex的区别也不是很大啊?
4. 我也看了看`ahooks`,是不是这个要和`ahooks`那种方式结合会好一些？

**Comment by plightfield** [comment]
Api改了，你可以看一下最新的文档
别管组件，现在是完全忽略组件的开发
需要的时候用个组件连接就行了
把ref当成一个对象
使用时只在watch和computed的时候处理它
不要管视图响应，让视图响应你，而不是你响应视图
至于类型，函数返回类型如果要你自己去一个个设置的话，没有用
Ahooks领域不一样，这个库只是用来处理脱离组件后的脱离关系
普及一下常识
逻辑能够写在(响应式)系统外，就是ioc，hooks，composition都是干这个的
全部逻辑写在系统在，是soa，ng service就是干这个的
全部逻辑写在系统外，并形成模块，领域，有自己的逻辑关系，就是ddd
这个时候框架只起到一个适配器的作用，框架的技术问题不在你编程考虑范围内
也就是说，组件不在你的逻辑范围内，组件只是一层皮

**Comment by plightfield** [comment]
对了，为啥token要全局维护？
class SomeService{
    static: getInjectionToken<SomeService>
}
SomeService.token = getInjectionToken(SomeService)
function SomeService(){}
但是注意，这个用法只能用在 module 上，内部涉及 aggregation 的地方不能用
因为 aggregate 系列方法需要处理 undefined 边界，类型有循环引用
内部用的时候，直接用 token 就行，因为 vue 没有 ng 那样的框架帮你初始化的机制，所以跨服务的类型推断是没有的
不过这也是好事，强制你为服务设置默认值，这样所有服务都可以独立变化

**Comment by plightfield** [comment]
https://zhuanlan.zhihu.com/p/345788034

**Comment by plightfield** [comment]
const token = getInjectionToken(SomeService)
function SomeService(){
}

**Comment by wangguo1230** [comment]
水平太低了,不是很懂,不好意思
